# Generated by Django 4.1.2 on 2022-10-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
